"""
Route: GET /api/v1/advisory  [Phase 6 — REAL]
Purpose: Return rule-based weather advisories derived from the Smart Alert Engine.

Phase 6: the advisory endpoint now returns real advisories generated by evaluating
live weather data against deterministic rules. No LLM involved.

Advisory vs Alert distinction:
  - Alerts  = urgent, time-limited warnings about dangerous conditions.
  - Advisories = practical guidance (general, health, outdoor, travel)
    derived from the same weather rules as alerts.
"""

import time
import uuid
import logging
from typing import Optional
from fastapi import APIRouter, Depends, Query
from app.schemas.advisory import Advisory, AdvisoryResponse, AdvisoryCategory
from app.schemas.weather import WeatherCurrent, WeatherForecast
from app.services.weather.service import WeatherService
from app.services.alerts.engine import AlertEngine
from app.schemas.alerts import AlertType, AlertSeverity

router = APIRouter()
logger = logging.getLogger(__name__)


def get_weather_service() -> WeatherService:
    return WeatherService()


def _build_advisories(
    current: WeatherCurrent,
    forecast: Optional[WeatherForecast],
    category: str,
) -> AdvisoryResponse:
    """
    Build practical advisories from current weather + alert engine results.

    For each triggered alert rule we generate one advisory, filtered by the
    requested category.  General advisories always include everything.
    """
    engine = AlertEngine()
    alerts = engine.evaluate(current, forecast)

    now = int(time.time())
    end = now + 86400  # valid for 24 h
    advisories: list[Advisory] = []

    alert_types = {a.alert_type for a in alerts}

    # ---------- heat advisory ----------
    if AlertType.HEAT in alert_types:
        heat = next(a for a in alerts if a.alert_type == AlertType.HEAT)
        if category in ("general", "health", "outdoor", "agriculture"):
            advisories.append(Advisory(
                advisory_id=f"adv-{uuid.uuid4().hex[:8]}",
                category=(
                    AdvisoryCategory.AGRICULTURE if category == "agriculture"
                    else AdvisoryCategory.HEALTH if category == "health"
                    else AdvisoryCategory.OUTDOOR
                ),
                title="Heat Safety Advisory",
                message=(
                    f"High temperature of {heat.relevant_value:.1f}°C detected. "
                    "Stay hydrated and avoid prolonged exposure during peak afternoon hours."
                ),
                recommendation=(
                    "Drink at least 2–3 litres of water per day. "
                    "Wear loose, light-coloured clothing. "
                    "Avoid strenuous outdoor activity between 11am and 4pm."
                ),
                valid_until=end,
            ))

    # ---------- rain advisory ----------
    if AlertType.RAIN in alert_types:
        rain = next(a for a in alerts if a.alert_type == AlertType.RAIN)
        if category in ("general", "travel", "outdoor", "agriculture"):
            advisories.append(Advisory(
                advisory_id=f"adv-{uuid.uuid4().hex[:8]}",
                category=(
                    AdvisoryCategory.AGRICULTURE if category == "agriculture"
                    else AdvisoryCategory.TRAVEL if category == "travel"
                    else AdvisoryCategory.GENERAL
                ),
                title="Rain Preparedness Advisory",
                message=(
                    f"Rain probability of {rain.relevant_value:.0f}% forecast. "
                    "Carry an umbrella and plan accordingly."
                ),
                recommendation=(
                    "Take a waterproof jacket or umbrella when going outdoors. "
                    "Avoid low-lying areas and check for road flooding if driving."
                ),
                valid_until=end,
            ))

    # ---------- wind advisory ----------
    if AlertType.WIND in alert_types:
        wind = next(a for a in alerts if a.alert_type == AlertType.WIND)
        if category in ("general", "travel", "outdoor", "agriculture"):
            advisories.append(Advisory(
                advisory_id=f"adv-{uuid.uuid4().hex[:8]}",
                category=(
                    AdvisoryCategory.AGRICULTURE if category == "agriculture"
                    else AdvisoryCategory.TRAVEL if category == "travel"
                    else AdvisoryCategory.OUTDOOR
                ),
                title="Wind Safety Advisory",
                message=(
                    f"Wind speeds of {wind.relevant_value:.0f} km/h expected. "
                    "Secure loose objects and use caution outdoors."
                ),
                recommendation=(
                    "Avoid exposed elevated areas. "
                    "Secure outdoor furniture and garden items. "
                    "Drive carefully — high-sided vehicles may be affected."
                ),
                valid_until=end,
            ))

    # ---------- UV advisory ----------
    if AlertType.UV in alert_types:
        uv = next(a for a in alerts if a.alert_type == AlertType.UV)
        if category in ("general", "health", "outdoor"):
            advisories.append(Advisory(
                advisory_id=f"adv-{uuid.uuid4().hex[:8]}",
                category=AdvisoryCategory.HEALTH if category == "health" else AdvisoryCategory.OUTDOOR,
                title="Sun Protection Advisory",
                message=(
                    f"UV index of {uv.relevant_value:.0f} — {uv.severity.value} solar radiation. "
                    "Protect your skin when outdoors."
                ),
                recommendation=(
                    "Apply broad-spectrum sunscreen (SPF 30+ for moderate; SPF 50+ for extreme). "
                    "Wear a wide-brimmed hat and UV-protective sunglasses. "
                    "Seek shade between 10am and 4pm."
                ),
                valid_until=end,
            ))

    # ---------- thunderstorm advisory ----------
    if AlertType.THUNDERSTORM in alert_types:
        if category in ("general", "travel", "outdoor", "agriculture"):
            advisories.append(Advisory(
                advisory_id=f"adv-{uuid.uuid4().hex[:8]}",
                category=(
                    AdvisoryCategory.AGRICULTURE if category == "agriculture"
                    else AdvisoryCategory.TRAVEL if category == "travel"
                    else AdvisoryCategory.GENERAL
                ),
                title="Thunderstorm Safety Advisory",
                message=(
                    "Thunderstorm conditions detected. "
                    "Stay indoors and avoid open exposed areas."
                ),
                recommendation=(
                    "Stay indoors away from windows. "
                    "Avoid using corded phones and unplug sensitive electronics. "
                    "Postpone outdoor activities until conditions improve."
                ),
                valid_until=end,
            ))

    # ---------- all-clear advisory ----------
    if not advisories:
        advisories.append(Advisory(
            advisory_id=f"adv-{uuid.uuid4().hex[:8]}",
            category=(
                AdvisoryCategory.AGRICULTURE if category == "agriculture"
                else AdvisoryCategory.GENERAL
            ),
            title="All Clear",
            message=(
                f"No significant weather hazards detected for "
                f"{current.location.city or 'your location'}. "
                "Conditions are suitable for outdoor activities."
            ),
            recommendation="Enjoy the day — no special weather precautions needed.",
            valid_until=end,
        ))

    return AdvisoryResponse(advisories=advisories, total=len(advisories))


@router.get("", summary="Get weather advisories", response_model=AdvisoryResponse)
async def get_advisory(
    lat: float = Query(0.0, description="Latitude"),
    lon: float = Query(0.0, description="Longitude"),
    category: str = Query("general", description="Advisory category: general | travel | agriculture | health | outdoor"),
    service: WeatherService = Depends(get_weather_service),
) -> AdvisoryResponse:
    """
    Returns weather-based advisories for the given coordinates.

    Advisories are generated using the same rule-based Smart Alert Engine
    as the /alerts endpoint, filtered by the requested category.

    No AI/LLM is used. All decisions are deterministic.

    [Phase 6 — REAL]
    """
    current = await service.get_current(lat, lon)
    forecast = await service.get_forecast(lat, lon, days=1)
    return _build_advisories(current, forecast, category.lower())
