"""
Route: GET /api/v1/alerts  [Phase 6 — REAL]
Purpose: Return weather alerts for a location using the Smart Alert Engine.

Phase 6 upgrade: now calls WeatherService.get_alerts_smart() which:
  1. Fetches real current + forecast weather from WeatherAPI.com.
  2. Runs the deterministic AlertEngine against the real data.
  3. Merges with any native WeatherAPI alerts.
  4. Returns a unified, de-duplicated AlertsResponse.
"""

from fastapi import APIRouter, Depends, Query
from app.schemas.alerts import AlertsResponse
from app.services.weather.service import WeatherService

router = APIRouter()


def get_weather_service() -> WeatherService:
    return WeatherService()


@router.get("", summary="Get weather alerts", response_model=AlertsResponse)
async def get_alerts(
    lat: float = Query(0.0, description="Latitude"),
    lon: float = Query(0.0, description="Longitude"),
    language: str = Query("en", description="Response language: 'en' | 'ta'"),
    lang: str = Query(None, description="Alias for language parameter: 'en' | 'ta'"),
    service: WeatherService = Depends(get_weather_service),
) -> AlertsResponse:
    """
    Returns active weather alerts for the given coordinates.

    Alerts are generated by the Smart Alert Engine using real-time
    weather data from WeatherAPI.com evaluated against configurable
    thresholds. No AI/LLM is used to decide whether an alert exists.

    [Phase 6 — REAL, Phase 8 — Multilingual]
    """
    selected_lang = lang or language or "en"
    return await service.get_alerts_smart(lat, lon, language=selected_lang)
